export const mockProfiles = [
  {
    id: "1",
    avatarUrl: "https://avatars.githubusercontent.com/u/583231?v=4",
    username: "octocat",
    followers: 150,
    following: 75,
    languages: ["JavaScript", "Ruby"],
  },
  {
    id: "2",
    avatarUrl: "https://avatars.githubusercontent.com/u/1?v=4",
    username: "torvalds",
    followers: 1200,
    following: 0,
    languages: ["C", "Python", "Shell"],
  },
  {
    id: "3",
    avatarUrl: "https://avatars.githubusercontent.com/u/2?v=4",
    username: "defunkt",
    followers: 800,
    following: 200,
    languages: ["Ruby", "JavaScript"],
  },
  {
    id: "4",
    avatarUrl: "https://avatars.githubusercontent.com/u/3?v=4",
    username: "pjhyett",
    followers: 600,
    following: 150,
    languages: ["Python", "Go"],
  },
  {
    id: "5",
    avatarUrl: "https://avatars.githubusercontent.com/u/4?v=4",
    username: "wycats",
    followers: 900,
    following: 300,
    languages: ["JavaScript", "Ruby", "Rust"],
  },
  {
    id: "6",
    avatarUrl: "https://avatars.githubusercontent.com/u/5?v=4",
    username: "ezmobius",
    followers: 400,
    following: 100,
    languages: ["Ruby", "Go"],
  },
  {
    id: "7",
    avatarUrl: "https://avatars.githubusercontent.com/u/6?v=4",
    username: "ivey",
    followers: 700,
    following: 250,
    languages: ["Python", "JavaScript"],
  },
  {
    id: "8",
    avatarUrl: "https://avatars.githubusercontent.com/u/7?v=4",
    username: "evanphx",
    followers: 500,
    following: 180,
    languages: ["Ruby", "JavaScript", "Go"],
  },
  {
    id: "9",
    avatarUrl: "https://avatars.githubusercontent.com/u/8?v=4",
    username: "vanpelt",
    followers: 300,
    following: 90,
    languages: ["Python", "Rust"],
  },
  {
    id: "10",
    avatarUrl: "https://avatars.githubusercontent.com/u/9?v=4",
    username: "wayneeseguin",
    followers: 450,
    following: 120,
    languages: ["Ruby", "JavaScript", "Python"],
  },
];
